version: 0.0
os: linux
files:
  - source: /
    destination: /opt/node
permissions:
  - object: /home/ubuntu
    owner: root
    group: group name if neccessary
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: deploy_scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy_scripts/run.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: deploy_scripts/validate.sh
      timeout: 60
      runas: root
